name: Java/Gradle CI

on: [push]
  # the following was not working:
  #push:
  #  tags-ignore:
  #    - 'v*' # ignore release tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install node dependencies
        run: npm install
        working-directory: ./hub/ui
      - name: Build with Gradle
        run: ./gradlew build
